version: '3'
services:
  app:
    build: .
    container_name: mono_docker
    volumes:
      - ./app:/home/app
      - ./example:/home/example
    networks:
      - default
    stdin_open: true
    tty: true
